// Notebooks
export const UPDATE_NOTEBOOK = 'UPDATE_NOTEBOOK';
export const ACTIVATE_NOTEBOOK = 'ACTIVATE_NOTEBOOK';

// World
export const TOGGLE_WORLD_DRAWER = 'TOGGLE_WORLD_DRAWER';
export const SAVE_NOTEBOOK_REQUEST = 'SAVE_NOTEBOOK_REQUEST';
export const SAVE_NOTEBOOK_COMPLETE = 'SAVE_NOTEBOOK_COMPLETE';


